### ISSUE TITLE
🗺 Roadmap + Specs

### ISSUE THREAD

**Issue by r002** [studydash/cards#75]
# _Last Updated Wednesday (9/15/21)_

## Next
- [ ] Add `multi-card` support per same day
<br />

## The Chromium Extension
Following the excellent documentation online, I've built a simple POC that allows me to inject html/css directly into the `GitHub Issue Editor`.  Here are other tasks remaining on the docket in this area:
- [ ] Finish the `Regex Parser` that powers the `Renderman` popup window.  This will allow me to hit `ctrl-s` anytime to easily preview the html of whatever I've written (without having to manually click on the `Preview` tab which is annoying)
- [ ] Serve the `testbed` as a static html page.  I can host this easily with `GitHub Pages`
<br />

## studydash.github.io
This is the `desktop site` of the dashboard.  Remaining tasks in this area:
- [ ] Add `Blog Roll` feature so each member can share their favorite people from around the web.
- [ ] Revamp `MembersPane`-- show visual meters and gauges that display a member's `Max Streak`, `Current Streak`, `Days Posted`, and `Days Missed`
- [ ] Figure out a clever way to show multiple cards per a single day.  (Right now, the system limits members to only showing one card per day.)
- [ ] Impl `auto-sync snippets` between `cards`
- [ ] Impl `Event Feed` RHS sidebar
- [ ] Impl `Weekly Summary Aggregator` that aggregates all cards/comment that pattern-match a certain format
  - Eg. `Weekly Reflection` entries like [this](https://github.com/studydash/cards/issues/94#issuecomment-855448835).
- [ ] Impl `Card Previewer` directly into the `dashboard`-- give a way to expand `cards` in `readonly-mode` without having to navigate to the GitHub site
- [ ] Impl `Private Cards`-- the ability to post `private cards` that point to a `private repo` but still have that card count as a `daily contribution`
<br />

## Mobile App?
This is a new idea that @shazahuang has requested.  It's been over a decade since I last looked at mobile app development (back in the days of early Android) but this is a good idea!  Shaza wants the ability to:
- [ ] Snap photos on your phone and then easily upload them to your daily contribution card in `StudyDash`
<br />

## Other Tasks
- [ ] Source `Go server` config values from `Firebase Remote Config`
- [ ] Add an `Overall Feed` that will show a timeline of selected events for all study group members
  - Eg. `Comment created/edited`, `Card edited`, `Card tag labeled/unlabeled` etc.
- [ ] Right-align `tag icons` on cards

**Comment by r002** [comment]
## New Features to Add
- [x] For `services` - Add an `/info` endpoint that will display `env details` and `config key names`
- [ ] A `Backup Button` - Clicking on the button should allow you to export all of your cards
  - Give option to only export a specific user's cards (add `login`?)
  - Give option to export _**all**_ cards
  - Give option to export between a specific `date range`
- [ ] A `Weekly Review Extractor` - A (serverless?) function that fires every time a [`Sunday Weekly Reflection`](https://github.com/r002/codenewbie/issues/94#issuecomment-855448835) is created.  Extract the `title` and summarize in `Feed`.
- [ ] Add `Feed` - A sidebar that shows selected events (comments, reactions, cards, Weekly Reflections) in real-time.

<br />

## Infrastructure Uplift
- [x] Make a proper `GitHub Release` of the `Dashboard GUI` - Merge current `sprint-grape` into `main`.  `0.6.27` ➡ `1.6.27` will become the first PROD version.  Then begin work on new [`sprint-hala`](https://github.com/r002/codenewbie/issues/72) branch.

<br />

## `Study Group` Specs
- [x] Connect the `dashboard` to `Firestore` via a real-time listener
- [ ] Write tests!  Add ability to generate GUI from `mock data`
- [x] Giant `Countdown Clock` -- displays time remaining (HH:MM:SS) until midnight of the current day
- [x] `Mousing-over` a card's `datetime` should show the exact `datetime` that the study group member created the card.
- [x] Add `<hr />` separators to demarcate weeks.  Every `Sunday - Saturday` constitutes a week.
- [x] Add `Top Bar`-- links to:
  - [x] [`🗺 Roadmap + Specs`](https://github.com/r002/codenewbie/issues/75)
  - [x] `GH JSON REST API endpoint`
  - [x] `GH Project Board`
  - [x] `GH Issues`
  - [x] `Group Members`
  - [x] `Changelog`
  - [x] `CodeNewbie` -- link to the original CodeNewbie article that started it all! 😀
- [x] Show an `🍿` icon on card if the card's been updated in the past ` 1 hour`.
- [ ] `Progress Summary` widget -- show which study group members have contributed (display past seven days)
- [ ] Rewrite GUI in `Svelte`
- [ ] Rewrite services in `Go`
- [ ] Impl `Max Streak`
- [ ] Build a parser that extracts `latest five comments` from all recent 100 posts
- [ ] Build a parser that extracts `links of the week` from all of posts; categorize by week
- [x] On `url aliases`-- show a `footer` displaying the `version number` and `build date` of the `release`
  - [x] https://r002.github.io/codenewbie/qa points to `latest QA build`
  - [ ] https://r002.github.io/codenewbie points to `latest PROD build`
- [x] Show number of comments that each card has received.  À la: 
  ![image](https://user-images.githubusercontent.com/45280066/118402517-334c6300-b638-11eb-8825-35e9240a8d82.png)

---

## GitHub API Endpoints
- https://api.github.com/repos/r002/codenewbie/issues?since=2021-05-03&labels=daily%20accomplishment&sort=created&direction=desc
- https://api.github.com/repos/r002/captains-log/branches
- https://api.github.com/repos/r002/captains-log/commits?sha=sprint-grape
- https://api.github.com/repos/r002/codenewbie/issues/24/comments
- https://api.github.com/repos/r002/codenewbie/issues?creator=r002
- https://api.github.com/repos/r002/codenewbie/issues?creator=anitabe404
- https://api.github.com/repos/r002/codenewbie/issues?creator=mccurcio
- https://avatars.githubusercontent.com/u/45280066?v=4
- https://avatars.githubusercontent.com/u/9167395?v=4
- https://avatars.githubusercontent.com/u/1915749?v=4

---

## References
- https://docs.github.com/en/rest/reference/issues
